

ALTER USER test DEFAULT tablespace users;
--users TABLE 공간 할당

ALTER USER test TEMPORARY tablespace temp; --temp TABLE 공간 할당

GRANT unlimited tablespace TO test; --tablespace 공간 무제한 부여

ALTER USER test account unlock; --새 사용자 잠김 해제


DROP TABLE DEPT;


CREATE TABLE DEPT(
    DEPTNO NUMBER(2) CONSTRAINT PK_DEPT PRIMARY KEY,
	DNAME VARCHAR2(14) ,
	LOC VARCHAR2(13) 
	) ;

INSERT INTO DEPT VALUES
	(10,'ACCOUNTING','NEW YORK');
INSERT INTO DEPT VALUES 
	(20,'RESEARCH','DALLAS');
INSERT INTO DEPT VALUES
	(30,'SALES','CHICAGO');
INSERT INTO DEPT VALUES
	(40,'OPERATIONS','BOSTON');
	

DROP TABLE EMP;

CREATE TABLE EMP
       (EMPNO NUMBER(4) CONSTRAINT PK_EMP PRIMARY KEY,
	ENAME VARCHAR2(10),
	JOB VARCHAR2(9),
	MGR NUMBER(4),
	HIREDATE DATE,
	SAL NUMBER(7,2),
	COMM NUMBER(7,2),
	DEPTNO NUMBER(2) CONSTRAINT FK_DEPTNO REFERENCES DEPT); --DEPT를 참조해 생성
	
	
	
INSERT INTO EMP VALUES
	(7369,
	'SMITH',
	'CLERK',	
	7902,
	to_date('17-12-1980', 'dd-mm-yyyy'),
	800,
	NULL,
	20);

INSERT INTO EMP VALUES
(7499,'ALLEN','SALESMAN',7698,to_date('20-2-1981','dd-mm-yyyy'),1600,300,30);

INSERT INTO EMP VALUES
(7521,'WARD','SALESMAN',7698,to_date('22-2-1981','dd-mm-yyyy'),1250,500,30);


SELECT to_char(sysdate, 'yyyy/mm/dd hh24')
FROM dual;
