SELECT ENAME 
FROM EMP  WHERE DEPTNO ='20';

SELECT ename, job, sal, deptno
FROM emp
WHERE DEPTNO=20 AND job='ANALYST';


SELECT * FROM EMP WHERE SAL=5000;
SELECT * FROM EMP WHERE SAL! =5000;
SELECT * FROM EMP WHERE SAL <>5000; 

SELECT * FROM EMP WHERE MGR = NULL; --불가능. IS / IS NOT 만 사용가능.

SELECT * FROM EMP WHERE ENAME=UPPER('scott') ; --ENAME 행의 컬럼 값이 SCOTT인 행을 대문자로

SELECT SYSDATE AS NOW, SYSDATE -1 AS YESTERDAY , SYSDATE +1 AS TOMORROW FROM DUAL; --오늘 어제 내일 출력

SELECT SYSDATE, ADD_MONTHS(SYSDATE,3) FROM DUAL;
SELECT SYSDATE, ADD_MONTHS(SYSDATE,35) FROM DUAL;

SELECT EMPNO, ENAME, HIREDATE, ADD_MONTHS(HIREDATE, 12*20) AS WORK20YEAR FROM EMP; 

SELECT ADD_MONTHS('2016-07-25', 12*10) AS WORK10YEAR FROM DUAL;  --나의 입사 10주년
 
SELECT EMPNO, ENAME, HIREDATE, SYSDATE  FROM EMP WHERE ADD_MONTHS(HIREDATE, 12*40) <SYSDATE ; 
--현재 입사 40주년 이상인 직원 조회. P158
 
SELECT ENAME, HIREDATE, SYSDATE
	,MONTHS_BETWEEN(HIREDATE,SYSDATE)/12 AS YEAR1 
	,MONTHS_BETWEEN(SYSDATE, HIREDATE)/12 AS YEAR2
	,TRUNC(MONTHS_BETWEEN(SYSDATE, HIREDATE)/12) AS YEAR3 FROM EMP ; 
-- P159
SELECT MONTHS_BETWEEN(SYSDATE ,'2016-07-25')/12 AS YEAR1  FROM DUAL;   